version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/
    steps:
      - run:
          name: Init env
          command: |
            git clone https://github.com/betagouv/pass-culture-main.git
            cd pass-culture-main
            rm -rf shared
            git clone https://github.com/betagouv/pass-culture-api.git api
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install -y nodejs yarn google-chrome-stable
      - checkout:
          path: ~/pass-culture-main/pro
      - run:
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Run API server
          command: |
            cd ~/pass-culture-main
            docker-compose up
          background: true
      - run:
          name: Run Frontend
          command: |
            export PATH=${PATH:44}
            export NVM_BIN=/usr/bin/nodejs
            export PATH=$NVM_BIN:$PATH
            cd ~/pass-culture-main/pro
            yarn install
            yarn start
          background: true
      - run:
          name: Running sandbox data import
          command: |
            cd pass-culture-main
            dockerize -wait http://localhost/health -timeout 5m -wait-retry-interval 5s
            ./pc sandbox --name=light

      - run:
          name: Run Functional Tests
          command: |
            export PATH=${PATH:44}
            export NVM_BIN=/usr/bin/nodejs
            export PATH=$NVM_BIN:$PATH
            cd ~/pass-culture-main/pro
            dockerize -wait http://localhost/health -timeout 5m -wait-retry-interval 5s
            yarn testcafe

workflows:
  version: 2
  commit:
    jobs:
      - build
