version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/
    steps:
      - run:
          name: Init env
          command: |
            git clone https://github.com/betagouv/pass-culture-main.git
            cd pass-culture-main
            rm -rf shared
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-api.git api || git clone https://github.com/betagouv/pass-culture-api.git api
            ./install_lib_ci.sh
      - checkout:
          path: ~/pass-culture-main/pro
      - run:
          name: Running Unit Tests
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use v8.15.1
            cd ~/pass-culture-main/pro
            yarn install
            yarn test:unit --coverage
            yarn coveralls
      - store_artifacts:
          path: ~/pass-culture-main/pro/coverage
      - run:
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Run API server
          command: |
            cd ~/pass-culture-main
            docker-compose up
          background: true
      - run:
          name: Run Frontend
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use v8.15.1
            cd ~/pass-culture-main/pro
            yarn install
            yarn start
          background: true
      - run:
          name: Running sandbox data import
          command: |
            cd pass-culture-main
            dockerize -wait http://localhost/health -timeout 5m -wait-retry-interval 5s
            ./pc sandbox --name=industrial

      - run:
          name: Run End To End Tests
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use v8.15.1
            cd ~/pass-culture-main/pro
            dockerize -wait http://localhost/health -timeout 5m -wait-retry-interval 5s
            yarn test:cafe
      - store_artifacts:
         path: ~/pass-culture-main/pro/testcafe_screenshots

workflows:
  version: 2
  commit:
    jobs:
      - build
