version: 2.1

###################
#  EXECUTORS
###################

executors:

  node-gcp:
    docker:
      - image: ${GCP_REGION}-docker.pkg.dev/${GCP_INFRA_PROJECT}/${GCP_TOOLS_REGISTRY_NAME}/node-gcp:12
        auth:
          username: _json_key  # default username when using a JSON key file to authenticate
          password: $GCP_INFRA_KEY

###################
#  REFERENCES
###################

references:

  working_directory: &working_directory
    ~/pass-culture-main/pro

###################
#  COMMANDS
###################

commands:

  authenticate_gcp:
    description: Authenticate to a GCP project
    parameters:
      gcp_key_name:
        type: env_var_name
    steps:
      - run: echo ${<< parameters.gcp_key_name >>} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}


  build:
    description: Build the pro webapp
    parameters:
      node_env:
        type: string
    steps:
      - run: |
          cd ~/pass-culture-main/pro
          yarn install

          set -a; source ~/pass-culture-main/config/run_envs/<< parameters.node_env >>;
          # TODO : Remove once env variables are cleaned in every app
          export NODE_ENV=<< parameters.node_env >>

          yarn build:testing

  push-to-bucket:
    description: Push the built webapp to a cloudstorage bucket
    parameters:
      bucket_name:
        type: string
      build_path:
        type: string
    steps:
      - run: |
          set +eo pipefail
          gsutil rsync -r << parameters.build_path >> gs://<< parameters.bucket_name >>
          true

###################
#  JOBS
###################

jobs:
  quality:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/
    steps:
      - run:
          name: Initialization environment
          command: |
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-main.git pass-culture-main || git clone https://github.com/betagouv/pass-culture-main.git pass-culture-main
            cd pass-culture-main
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-api.git api || git clone https://github.com/betagouv/pass-culture-api.git api
            ./install_lib_ci.sh
      - checkout:
          path: *working_directory
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/pass-culture-main/pro/yarn.lock" }}
      - run:
          name: Install dependencies
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/pass-culture-main/pro/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Running linter
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn lint:js

  run-unit-tests:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/
    steps:
      - run:
          name: Initialization environment
          command: |
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-main.git pass-culture-main || git clone https://github.com/betagouv/pass-culture-main.git pass-culture-main
            cd pass-culture-main
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-api.git api || git clone https://github.com/betagouv/pass-culture-api.git api
            ./install_lib_ci.sh
      - checkout:
          path: *working_directory
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/pass-culture-main/pro/yarn.lock" }}
      - run:
          name: Install dependencies
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/pass-culture-main/pro/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Running Unit Tests
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn test:unit --coverage --silent
            yarn coveralls
            bash <(curl -s https://codecov.io/bash)

  run-e2e-tests:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/
    steps:
      - run:
          name: Initialization environment
          command: |
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-main.git pass-culture-main || git clone https://github.com/betagouv/pass-culture-main.git pass-culture-main
            cd pass-culture-main
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-api.git api || git clone https://github.com/betagouv/pass-culture-api.git api
            ./install_lib_ci.sh
      - checkout:
          path: *working_directory
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/pass-culture-main/pro/yarn.lock" }}
      - run:
          name: Install dependencies
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/pass-culture-main/pro/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Install dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Running API server
          command: |
           cd ~/pass-culture-main
           ./pc start-backend
          background: true
      - run:
          name: Running Frontend
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn start
          background: true
      - run:
          name: Running industrial sandbox
          command: |
            cd pass-culture-main
            dockerize -wait http://localhost/health/api -timeout 5m -wait-retry-interval 5s
            dockerize -wait http://localhost/health/database -timeout 5m -wait-retry-interval 5s
            ./pc sandbox --name=industrial
      - run:
          name: Running end2end tests
          working_directory: *working_directory
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install
            yarn test:cafe
      - store_artifacts:
         path: ~/pass-culture-main/pro/testcafe_screenshots

  deploy-pro:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/
    steps:
      - run:
          name: Checkout main
          command: |
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-main.git pass-culture-main || git clone https://github.com/betagouv/pass-culture-main.git pass-culture-main
      - checkout:
          path: ~/pass-culture-main/pro
      - run:
          name: Install Lib CI
          command: |
            cd ~/pass-culture-main/pro
            ./scripts/install_lib_ci_pro.sh
      - run:
          name: Build and Deploy
          command: |
            cd ~/pass-culture-main/pro
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
            nvm install
            yarn install

            set -a; source ~/pass-culture-main/config/run_envs/testing

            yarn build:testing
            npm install -g netlify-cli@2.46.0
            netlify deploy -s "${NETLIFY_SITE_ID_PRO}" -a "${NETLIFY_TOKEN}" -d build/ --prod

  deploy-pro-gcp:
    executor: node-gcp
    steps:
      - run:
          name: Checkout main
          command: |
            git clone --single-branch --branch $CIRCLE_BRANCH https://github.com/betagouv/pass-culture-main.git ~/pass-culture-main || git clone https://github.com/betagouv/pass-culture-main.git ~/pass-culture-main
      - checkout:
          path: ~/pass-culture-main/pro
      - authenticate_gcp:
          gcp_key_name: GCP_METIER_KEY
      - build:
          node_env: testing
      - push-to-bucket:
          build_path: ~/pass-culture-main/pro/build/
          bucket_name: ${GCP_PROJECT}-testing-pro

###################
#  WORKFLOWS
###################

workflows:
  version: 2
  commit:
    jobs:
      - run-unit-tests
      - run-e2e-tests
      - quality
      - deploy-pro:
          filters:
            branches:
              only:
                - master
          requires:
            - run-unit-tests
            - run-e2e-tests
            - quality

  gcp:
    jobs:
      - deploy-pro-gcp:
          filters:
            branches:
              only:
                - master
          context:
            - GCP
            - GCP_EHP
